iprange/iprange.go
iprange/iprange_test.go

added subnet overlap check to iprange along with unit tests
added subnet overlap func to iprange

added subnet overlap func to iprange

---

.travis.yml

Add travis ci integration to the util repo

---

docker/registry.go

Include Docker registry response body in error.

---

docker/registry_url.go
docker/registry_url_test.go

Ready for merge.
Signed-off-by: Jon Poler <jonathan.poler@apcera.com>

Added logic to parse Docker Registry URLs.

---

docker/registry_url.go
docker/registry_url_test.go

Add function BaseURL which includes credentials, and SchemeHostPort which doesn't.
Also refactor tests to use anonymous structs.

Add function to retrieve registryURL without user credentials.

---

docker/registry.go
docker/registry_url.go
docker/registry_url_test.go
dockertest/dockertest.go
taskrenderer/renderer.go

Add docker handler

---

taskrenderer/renderer.go

Update task renderer to be compatible with client changes.

Docker v none

---

tarhelper/tar.go
tarhelper/tar_test.go
tarhelper/utils_posixfs.go
tarhelper/utils_windows.go

@krobertson @olegshaldybin @mbhinder

Fix mode logic to preserve setuid bit

---

docker/registry_url.go
docker/v1/registry.go
docker/v1/registry_test.go
docker/v2/registry.go
dockertest/v1/mock_v1_registry.go
dockertest/v2/mock_image_manifests.go
dockertest/v2/mock_v2_registry.go

docker/test: split v1/v2 registry code; add mock v2 registry

---

dockertest/v2/mock_v2_registry.go

Exposing a setting to skip authorization (and any challenges)
allows us to unit test against an unauthenticated registry, which
mirrors a lot of private registry setups.
@wallyqs @jpoler @hyingyang

dockertest/v2: allow skipping auth challenges

---

wsconn/websocket_connection.go

@krobertson @wallyqs 
Should have noticed that this was OpPong when I updated this library awhile ago... Oops

Write ping messages on a timer; instead of pong messages.

---

tarhelper/untar.go

Windows has a max path length of 260 chars. Throw an
error if the path length is exceeded when a file is
extracted.
Resolves [ENGT-7861](https://apcera.atlassian.net/browse/ENGT-7861).

Check path len of extracted files on Windows

---

tarhelper/tar.go
tarhelper/tar_test.go

Expands the capabilities to specify files in a given tar:
- Allows for subsequent regexps to reinclude files or directories
- Allows for specifying that the file must also be a directory to qualify as a match
@zquestz @variadico @y0ssar1an

tarhelper: Expand ignore capabilities

---

restclient/restclient.go

Allow restclient to support disabling of HTTP keep-alives. Just offers another constructor `NewDisableKeepAlives()` to accomplish this so the default behavior has not changed.
When keepalives are disabled, we also set `req.Close = true` to close the connection once it has been sent.
@krobertson @wallyqs @shobhit85

Allow restclient to specify if keepalives should be used

---

docker/registry_url.go
docker/registry_url_test.go

The eventual use of the user info string is for placement into
basic auth headers which get base64 encoded and do not expect
to be percent encoded. As a result, auth will fail unless you
unescape this string later.
This change removes the need to unescape by setting the user info
with the raw username and password.
@alextoombs @wallyqs @shobhit85 
fyi @tedtong

docker: store user info in *url.Userinfo instead of string 

---

tarhelper/tar.go
tarhelper/tar_test.go
tarhelper/untar.go
tarhelper/untar_test.go

This adds support for a CustomHandler slice onto Tar and Untar. This
allows the caller to pass in function handlers that can be called to
customize the handling around specific entries.
Support to inject custom transformations is necessary to handle inline
conversion handlers for multiple union filesystems in the Continuum
codebase. We'll have this work by on the fly adapting to/from what we'll
officially utilize in the base packages to what the local host is
configured to use.
Change is part of #ENGT-9504.
review: @zquestz @jpoler 
cc: @earlruby

tarhelper: Add support for custom entry handlers on tar/untar

---

docker/v1/registry.go
s3util/s3util.go

Continuation of the work done at https://github.com/apcera/continuum/pull/5626
@krobertson @wallyqs @lilirui @variadico

Fix EOF and connection reset errors due to keepalives

---

.travis.yml

Remove GO15VENDOREXPERIMENT which is unnecessary.
Remove go fmt call which didn't do anything.
Remove redundant go test -i call.

Update Go versions in travis file to 1.6.4 and 1.7.4

---

dockertest/v2/mock_v2_registry.go

Accompanies https://github.com/apcera/continuum/pull/5850

Add slash to v2 endpoint

---

restclient/restclient.go
restclient/restclient_test.go

There are other media types which contain JSON data and should
work with our rest client. If it is not JSON data, trying to
decode it will cause an error anyways. This only has leads to
different error messages when decoding invalid JSON and when
getting something that is JSON but a different media type.

restclient: Allow content-type headers besides application/json

---

testtool/channel.go

Add channel assertions.

---

testtool/gettestdata.go
testtool/testtool.go

So that it can be used in benchmarking contexts

testtool to use testing.TB instead of *testing.T

---

testtool/gettestdata.go
testtool/gettestdata_test.go

Fixes #ENGT-11909, relates to #ENGT-11837

testtool: make it work with Benchmarks and sub-tests
