apcera/util

aciremote/remote.go
uuid/uuid_test.go

Also, the benchmark around the built-in string method
is well known and thus the benchmark didn't provide much value.
FYI PR @krobertson

Address go vet.

---

tarhelper/tar.go
tarhelper/utils_posixfs.go
tarhelper/utils_windows.go

Windows does not support the idea of an 'executable' bit on permissions.
As a result, no file tar'd on Windows would be executable causing many apps
to fail.  This included simple demo ruby/bash apps.  This fix just causes
everything tar'd on a Windows machine to be marked as executable.
Ideally the fix would be a little more fine grained, but this seems to be
the only way to ensure that all files needed as +x are marked as such.  In
Windows, its almost as if all files are executable so this seems to be in
line with their approach.
Docker's Window CLI faced this same concern and so our code fix and approach
mirror theirs.  See https://github.com/docker/docker/issues/11047

Windows Permissions

---

tarhelper/untar.go
tarhelper/utils_posixfs.go
tarhelper/utils_windows.go

This updates the wrappers for Windows compatibility on umask to return the old
umask.
This updates the mknod handling, which already was doing umask(0) to ensure it
resets the umask back after it is done.
This also updates the chmod and create operations operations done to regular
files/directories to be wrapped in a umask(0) operation and ensure the umask
is reset after the chmod.
The handling does not reset with a defer to ensure the umask is reset
immediately before any other file operations might be done.
@tcahill @olegshaldybin

Fix handling of umask around chmod operations.

---

tarhelper/untar.go
tarhelper/utils_posixfs.go
tarhelper/utils_windows.go

This changes places that relied upon setting the umask to instead use an
explicit chmod. This is more explicit and saver, as it avoids altering the
process wide umask which may not be safe with multiple goroutines.
@olegshaldybin @tcahill @philpennock

Move away from setting umask at all and use explicit chmod.

---

tarhelper/tar.go
tarhelper/tar_test.go

This addresses a bug (#ENGT-1779) where an invalid tarball was created when
tarhelper.NewTar is pointed directly at a file rather than a directory.
Previously, it would create a tarball with the file just fine, but the file in
the tarball would be named ".".
When then untaring the file, it would simply not work too well. If the
NewUntar path already existed, it would error, or if it didn't exist, create
the target but the caller is often expecting a path, while it would create it
as a file.
This change improves the handling, where when it is pointed at a file, it will
tar just the file, but preserve its filename as the entry, and when the same
file is untarred, the target would be a path and it would contain the
specified file.
@alextoombs @klobucar

Improves handling when Tar is pointed directly at a file.

---

docker/registry.go
docker/registry_test.go

The status code is useful for determining whether a request is denied because it lacks credentials.

GetImage now returns status code as a return value.

---

docker/registry.go

Return -1 on error from client.Do instead of status code.

---

tarhelper/untar.go

The file modes was not being preserved properly because of an improper
use of the tar header.
Fixes #ENGT-3239.
@philpennock @krobertson

Fix untar file modes.

---

terminal/terminal_colors_unix.go
terminal/terminal_colors_windows.go

Uses basic color set which can be utilized by other libraries to use kernal32.dll to colorize Windows command line output.

Add basic color support for windows

---

terminal/terminal_state_windows.go

This addresses some of the needs of terminal handling on Windows.  Most importantly for now, Isatty works as intended.
Adapted from golang.org/x/crypto/ssh/terminal

Add some terminal handling for Windows

---

taskrenderer/renderer.go
taskrenderer/taskevent.go

This renderer acts as a simple append-only logger. The main idea
is that the renderer formats incoming TaskEvents in a human-readable
way. TaskEvents will be provided to the renderer via a channel, and
the renderer will output them to the specified io.Writer.
replaces #17 because Github doesn't let you switch target branches for a PR.
@shobhit85 @wallyqs @olegshaldybin @alextoombs

Add a package to render TaskEvents from the Task API Framework.

---

tarhelper/untar.go
tarhelper/untar_test.go

The untar package had some paths that were specific to Unix, added some
logic to create them differently depending on the platform.
Also, the chmod function does not work on Windows, added a helper called
`chmod` which is a noop on Windows.
@apcera/cloud-services

Fixed untar on the Windows platform

---

procstat/procstat_darwin.go
procstat/procstat_linux.go
procstat/types.go

This adds a function which can be used to calculate a process's CPU
and memory usage via the /proc filesystem. This is mostly intended for
use in common component, which currently shells out to ps to do this.
Additionally, this moves towards CPU usage being shown in cumulative
time rather than doing a percentage. Percentage is already doing an
average over the number of CPUs and implies some timewindow to it. The
raw time spent is a rawer metric.
@olegshaldybin @alextoombs

Adds package for gathering a process's CPU and memory usage.

---

.travis.yml
tarhelper/tar.go
tarhelper/tar_test.go

Added option to ignore ./ in the tar header. This fixes a bug reported to Derek when expanding the gnatsd release file. 
@krobertson @wallyqs @derekcollison

Added flag to allow user to exclude ./ so untarring doesn't modify the parent directory

---

docker/registry_url.go
docker/registry_url_test.go

Passing in an image name of `httpd` would cause the parsing function to treat
the input as a partial image name, rather than a URL.
@wallyqs @jpoler

docker: handle scheme-ish image names

---

docker/registry_url.go
docker/registry_url_test.go

When a user supplies a partial Docker registry URL, we should parse that
with https enabled by default.
@wallyqs @jpoler @olegshaldybin 
This code is getting kind of ugly.

docker registry URL: parse with https default

---

.travis.yml
proc/proc_test.go

Was getting an error when attempting to retrieve go vet. I don't know why we were doing this, since it appears to already be present. Other repos weren't retrieving it anymore.
Upstream libraries from AppC discovery and some of its dependencies were no longer Go 1.3 compatible. We don't use 1.3 either. So removed testing on 1.3 and added in testing on 1.6.

Fix travis tests

---

envmap/envmap.go
envmap/envmap_test.go

This fixes EnvMap to have exported fields so that it can be properly
marshalled/unmarshalled into JSON.
This fixes an issue where internally, we were attempting to marshal an
EnvMap to cache its state on disk. However, it was being written as an
empty map.
This also adds a simple marshal/unmarshal test and validate the map
resolves the same as before.
#ENGT-7714
@zquestz @alextoombs

envmap: Fix envmap to be able to be JSON marshalled

---

tarhelper/untar.go

We encountered a problem in `apcera-setup` on Windows where the `orchestrator` and `deploy` .ova images did not extract to the correct directory.
```
C:\Users\foo\apcera-setup\
images\
trusty-deploy-virtualbox.tar.gz
trusty-deploy-virtualbox-latest.ova
C:\Users\foo\apcera-setup\
images\trusty-deploy-virtualbox.tar.gz
Users\
foo\
apcera-setup\
images\
trusty-deploy-virtualbox-latest.ova
```
`tarhelper` was being given an _absolute_ destination path like `C:\Users\foo\apcera-setup\images\foo.ova` and was treating it like a _relative_ path. This happened because the `\` was being stripped from `C:\` in `resolveDestination`. This patch reinserts the slash after it has been stripped.
Props to @mbhinder for the fix.
Fixes ENGT-7846
@mbhinder @krobertson @alextoombs

Fix bug with Windows absolute paths

---

dockertest/v2/mock_v2_registry.go

The `docker2aci` client expected this value, but our mock registry was
not returning the header properly. This brings the mock registry closer
in-line with the v2 registry API spec.
@wallyqs @krobertson @mbhinder

dockertest/v2: return expected registry header

---

.travis.yml
restclient/restclient.go

Just removes the ResponseHeaderTimeout to avoid errors like:
http://tc.apcera.net/viewLog.html?buildId=251619&buildTypeId=SystemTests_MasterTesting_DeployTestMasterAwsMultiCentral&tab=buildLog#_focus=907
@krobertson @tw4dl @variadico @mbhinder @shobhit85 @kelingel

Don't set ResponseHeaderTimeout for restclient

---

dockertest/v2/mock_v2_registry.go

Looking to unblock some Kurma unit tests. Query parameters are not required to be supplied in a specific order.
@tcahill @wallyqs @krobertson

Change mock v2 registry to better handle scope and service

---

.travis.yml
restclient/restclient.go

Reverts apcera/util#48 for now to reduce our suspicious numbers, at least it didn't fix the problem, we can reopen it later if we find out the root cause.
@krobertson @zquestz @wallyqs @shobhit85

Revert "Don't set ResponseHeaderTimeout for restclient"

---

tarhelper/untar.go

This fixes an issue which can happen if the first entry in a tar file is
a file entry within a directory, and not a tar entry to create the
directory. For instance, doing `tar foo.tar app/*`, there won't be an
entry for `app/` in the tar file.
Tarhelper would automatically create the destination path, however it
was using a MkdirAll, which could create multiple directory elements,
and then was chowning only the last element. Further, it was doing the
chown without calling to OwnerMappingFunc/GroupMappingFunc, which is
what we use to apply user namespace offsets.
This would mean within the container, the directory path would exist but
with owners the container couldn't access.
Fixes #ENGT-6060
@olegshaldybin @alextoombs

tarhelper: Ensure auto-created target directory gets owners mapped

---

events/stream.go

I noticed a tiny issue in `events`. There's a ticker that needs to be stopped at exit. This is described in the docs here: https://golang.org/pkg/time/#NewTicker
@alextoombs

Fix ticker leak

---

docker/v1/registry_test.go
envmap/envmap_test.go
hmac/hmac_test.go
proc/parser_test.go
proc/proc_test.go
restclient/restclient_test.go
tarhelper/tar_test.go
tarhelper/untar_test.go
testtool/childcleaner.go
testtool/equal.go
testtool/equal_test.go
testtool/gettestdata.go
testtool/testtool.go

Main changes:
- Iterate over the unexported fields as well. Since we can't call `Interface()` on unexported fields, we at least check their string representations. There are other golang diff libraries that work this way as well.
- Update method signatures to match our expectations
Other changes:
- Fixup a number of comments
- Add more test cases to test new functionality
- Add TestNoMatch method; needed method for another repo
- Update other tests/references to be compatible with these changes and consistent with other uses (using a named import rather than `.`)
- Add extra logging in the test of TestEquals
- Remove the `--debug` flag as it is difficult/impossible to use when using `go test ./...` since some packages may not be able to build due to no buildable source. The presence of …

Unexported fields

---

docker/v1/registry_test.go
envmap/envmap_test.go
hmac/hmac_test.go
proc/parser_test.go
proc/proc_test.go
restclient/restclient_test.go
tarhelper/tar_test.go
tarhelper/untar_test.go
testtool/childcleaner.go
testtool/equal.go
testtool/equal_test.go
testtool/gettestdata.go
testtool/testtool.go

- Previously we were skipping over unexported fields silently which
gives misleading results in many situations (e.g. two different
byte buffers with different contents would pass TestEqual). Included
many changes to how deepValueEquals iterates over values.
- Added one more helper (TestNotMatch).
- Updated method signatures to match expectations in our other codebase
including creating a TestTool object rather than relying only on global
state.
- Misc readability fixes

testtool: Use DeepEqual

---

uuid/uuid.go

Fix typo in FromBytes method which evidently has never been used until now.
@schancel - just for another set of eyes. This fix is required for my PR on continuum.

Use correct variable when checking input

---

testtool/equal.go

When you expect nil but get non nil the current message does
not give enough information for debugging. It should describe
what you actually got.

testtool: Add more info when describing non-nil result

---

testtool/channel.go

Moving SendWithCancel here to avoid code repetition.

testtool: Add SendWithCancel for general signaling.

---

tarhelper/tar.go
tarhelper/tar_test.go

CustomHandler[] callbacks can only modify the headers of existing files.  PrefixHook and SuffixHook add the ability to insert additional headers or file data into the archive. 
This will be used to insert the base whiteout file ( ./..wh.wh.aufs ) when tar'ing Overlayfs based layers into the AUFS format used in packages.  All other whiteout files are a hardlink of the base whiteout file.

tarhelper - Option to prefix or suffix files/headers in the archive.
